describe "hipbone", ->
  require("./module_spec").apply(this)
  require("./i18n_spec").apply(this)
  require("./identity_map_spec").apply(this)
  require("./storage_spec").apply(this)
  require("./application_spec").apply(this)
  require("./model_spec").apply(this)
  require("./collection_spec").apply(this)
  require("./router_spec").apply(this)
  require("./route_spec").apply(this)
  require("./view_spec").apply(this)
